@startuml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.1.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/font-awesome/laptop.puml
!includeurl ICONURL/font-awesome/key.puml

!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!includeurl CLOUDOGUURL/dogus/cloudogu.puml  
!includeurl CLOUDOGUURL/tools/k8s.puml

!define CLOUDOGU_BLUE #23a3dd

title <color:blue><$k8s></color> **Authentication and Authorization** <color:blue><$k8s></color>\n

rectangle "<color:BLUE><$k8s></color>\nKubernetes API Server" as k8s
rectangle "Role Based Access Control (RBAC)" as RBAC
rectangle "<$laptop>\nUser" as user
rectangle "<$key>\nIdentity Provider" as ID

user -> k8s : 1: Pass Credentials
k8s <-> ID : 2: Verify Identity
k8s <--> RBAC : 3: Check Authorization
k8s -> user : 4: Allow/deny

legend
<color:#23a3dd><$cloudogu></color> [[https://cloudogu.com cloudogu.com]]
end legend

skinparam arrow {
    Color CLOUDOGU_BLUE
}

skinparam rectangle {
    BackgroundColor WHITE
    BorderColor CLOUDOGU_BLUE
    FontColor BLACK
}

skinparam legend {
    BackgroundColor WHITE
    BorderColor #16688d
}

@enduml