@startuml

!include <tupadr3/common>

!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014

!includeurl https://raw.githubusercontent.com/michiel/plantuml-kubernetes-sprites/master/resource/k8s-sprites-unlabeled-25pct.iuml
!includeurl ICONURL/Devices/load_balancer.puml

!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!includeurl CLOUDOGUURL/dogus/cloudogu.puml  
!includeurl CLOUDOGUURL/tools/k8s.puml

!define CLOUDOGU_BLUE #23a3dd

' Remove this line for transparent background
skinparam backgroundColor #FFFFF0

title <color:blue><$k8s></color> **Rolling updates explained** <color:blue><$k8s></color>\n


rectangle "Version 1.0 active" as 1 <<rollingUpdateGroup>> {
    rectangle "<$svc>\nService" as service_1
    rectangle "<$pod>\n1.0\nactive" as pod_1_1
    rectangle "<$pod>\n1.0\nactive" as pod_1_2
    rectangle "<$pod>\n1.0\nactive" as pod_1_n
    
    service_1 --> pod_1_1
    service_1 --> pod_1_2
    service_1 --> pod_1_n
}

rectangle "Begin rolling update" as 2 <<rollingUpdateGroup>> {
    rectangle "<$svc>\nService" as service_2
    rectangle "<$pod>\n2.0\ndeploying" <<rollingUpdateGroup>> as pod_2_1
    rectangle "<$pod>\n1.0\nactive" as pod_2_2
    rectangle "<$pod>\n1.0\nactive" as pod_2_n
    
    service_2 -[hidden]-> pod_2_1
    service_2 --> pod_2_2
    service_2 --> pod_2_n
}

rectangle "Both versions active" as 3 <<rollingUpdateGroup>> {
    rectangle "<$svc>\nService" as service_3
    rectangle "<$pod>\n2.0\nactive" as pod_3_1
    rectangle "<$pod>\n2.0\ndeploying" <<rollingUpdateGroup>> as pod_3_2
    rectangle "<$pod>\n1.0\nactive" as pod_3_n
    
    service_3 --> pod_3_1
    service_3 -[hidden]-> pod_3_2
    service_3 --> pod_3_n
}

rectangle "Version 2.0 active" as 4 <<rollingUpdateGroup>> {
    rectangle "<$svc>\nService" as service_4
    rectangle "<$pod>\n2.0\nactive" as pod_4_1
    rectangle "<$pod>\n2.0\nactive" as pod_4_2
    rectangle "<$pod>\n2.0\nactive" as pod_4_n
    
    service_4 --> pod_4_1
    service_4 --> pod_4_2
    service_4 --> pod_4_n
}

pod_1_1 -[hidden]-- pod_3_1
pod_2_1 -[hidden]-- pod_4_1

legend
<color:#23a3dd><$cloudogu></color> [[https://cloudogu.com cloudogu.com]]
end legend

skinparam arrow {
    Color CLOUDOGU_BLUE
    FontColor WHITE
}

skinparam rectangle {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
    FontColor WHITE
    
    backgroundColor<<rollingUpdateGroup>> WHITE
    FontColor<<rollingUpdateGroup>> CLOUDOGU_BLUE
}

skinparam legend {
    BackgroundColor WHITE
    BorderColor #16688d
}
@enduml
