@startuml

!include <tupadr3/common>

!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014

!includeurl https://raw.githubusercontent.com/michiel/plantuml-kubernetes-sprites/master/resource/k8s-sprites-unlabeled-25pct.iuml
!includeurl ICONURL/Devices/load_balancer.puml

!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!includeurl CLOUDOGUURL/dogus/cloudogu.puml  
!includeurl CLOUDOGUURL/tools/k8s.puml

!define CLOUDOGU_BLUE #23a3dd

title <color:blue><$k8s></color> **Services, Nodes and Pods explained**<color:blue><$k8s></color>\n

rectangle "<$load_balancer>\nLoad Balancer" as LB

cloud "K8s Cluster" as k8s { 

together {
    rectangle "<$node>\nNode n" as node_n <<node>> {
        rectangle "<$svc>\nService" as service_n
        rectangle "<$pod>\nPod n" as pod_n
    }
    
    rectangle "<$node>\nNode 1" as node_1 <<node>> {
        rectangle "<$svc>\nService" as service_1
        rectangle "<$pod>\nPod 1" as pod_1
        rectangle "<$pod>\nPod 2" as pod_2
    }
     }
}

LB -[hidden]-> k8s

service_1 -[hidden]-> pod_1
service_1 -[hidden]-> pod_2
service_n -[hidden]-> pod_n

LB -> service_1
LB -> service_n

service_1 --> pod_1
service_1 --> pod_2
service_1 --> pod_n

service_n --> pod_1
service_n --> pod_2
service_n --> pod_n

legend
<color:#23a3dd><$cloudogu></color> [[https://cloudogu.com cloudogu.com]]
end legend


skinparam arrow {
    Color CLOUDOGU_BLUE
    FontColor WHITE
}

skinparam rectangle {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
    FontColor WHITE
    
    backgroundColor<<node>> WHITE
    FontColor<<node>> CLOUDOGU_BLUE
}

skinparam legend {
    BackgroundColor WHITE
    BorderColor #16688d
}

@enduml
